name: Ruby

on:
  push:
    branches:
      - master
      - development

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Main Pipeline
    strategy:
      matrix:
        ruby:
          - '3.1.2'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install dependencies
      run: make install
    - name: Run Rubocop
      run: make lint
    - name: Run RSpec
      run: make test